### PR TITLE
remove temp files created by riot

### PR DESCRIPTION
**Pull request by jdhayhurst**
- Remove the temp file created during the riot process
- resolves opentargets/issues#3054

### CODE REVIEW

**Review by ehsanb29 — APPROVED** [review]
Good Idea!
Thank you @jdhayhurst!

**Comment by mbdebian** [comment]
> Good Idea!
> Thank you @jdhayhurst!
> I added @mbdebian as reviewer to have a look at this change to double check.

Ok, let's scope the problem and the work that should fix it.

The problem is the following:
> We use the RIOT + JQ tandem to convert an ontology file into _JSON_ representation and then apply some filtering.
In the process, a temporary asset is created, which is the unfiltered _JSON_ representation of the ontology data.
This temporary artifact is internal to the conversion process, i.e. the way we go from an ontology file to a _JSON_ file that contains that ontology data in _JSON_ format after some additional filtering belongs to the inner workings of the method, the outside world doesn't, and shouldn't, know how that task is performed, it belongs to the abstraction.

Taking this into account, we just need a non-clashing location for our temporary data, this location is not constrained by the client of the method, and now known by the world outside the implementation of this process, in UNIX systems we have a method to ask the OS for this kind of temporary location, and the OS takes care of everything:
- Making sure it doesn't clash with any other thing in the environment
- Abstracting the client code from how that's implemented (local FS, NFS, memory FS, a Database backend...), it doesn't matter
- Making sure we can read / write to that location
- Potentially taking care of cleaning up after, when we no longer need that temporary location.

In a _shell script_ this is achieved by a _mktemp_ call, and, in the case we'd like to clean things up, by also setting a _TRAP_.

If we use this mechanism, asking for a temporary folder, the benefits would be:
- We don't need to worry about where in the file system
- The folder name is unique for every call requesting a temporary location, so we don't even need to randomize the file names we'd be writing there
- We (potentially) don't need to clean after, specially taking into account that:
  - When running in a container, we won't keep the image used, as we always pull
  - The pipeline is meant to run on a disposable VM on GCP, so everything goes, afterwards, we just keep the collected data in the GCS bucket.
  - Even when running outside of a container, on a VM or your laptop, the OS will provide you with a temporary location in the system that it's either automatically cleaned up on reboot, or just dies with the disposable VM

This means we don't even need that additional unit test that is attached to the PR.

On the side, we also need to think about the _Path_ objects leaking up the food chain to the manifest file _destination path_ attribute, which is crashing the method that converts all those paths into relative paths.

My preferred approach, taking into account we don't use _pathlib_ anywhere else in the pipeline, would be to refactor the code that uses it by switching to _os.path_ calls, so we keep processing paths through their string representation, as it's very likely that many other places in the pipeline are counting on it to be that way.

**Review by mbdebian — CHANGES_REQUESTED** [review]
Hi @jdhayhurst , would you mind having a look at my comments in the main conversation thread and coordinating with @ehsanb29 to fix together the three issues he raised?
Thanks!

**Review by ehsanb29 — APPROVED** [review]
Thank you @jdhayhurst!

**Review by mbdebian — APPROVED** [review]
This looks pretty good!
Thanks @jdhayhurst !
🕺🏻 🎉

**Pull request merged**
