### PR TITLE
OpenFDA FAERS Data Gathering step

### PR DESCRIPTION
**Pull request by mbdebian**
This pull request contains the code for gathering OpenFDA FAERS data and the blacklisted events for the ETL backend pipeline.

### CODE REVIEW

**Comment by mbdebian** [comment]
Please, don't process this request yet, as I need to include an extra step for the resulting OpenFDA data

**Comment by mbdebian** [comment]
Done, I have now fixed the bug in my pull request, and the output can be loaded in Spark correctly.
I know this version comes with no tests, but I thought of including the data gathering code for it to be available for the release at the end of the month, while I write tests for it.
Please, let me know what you think.
Thanks,
Manuel

**Comment by mbdebian** [comment]
I just merged the most recent changes from 'master' as well.

**Comment by mbdebian** [comment]
For some reason it's not triggering Travis CI, but it should work, as the only complaint was the missing updates from 'master'

**Review by cmalangone — APPROVED** [review]
Fix the conflict and everything seems fine

**Pull request merged**
